### ISSUE TITLE
software compatiblity

### ISSUE THREAD

**Issue by Waleed-Ahmed-Khan** [hellloxiaotian/BRDNet#7]
hi i am tring to run your code in pycharm but there is many error as you use ubuntu so kindly tell me is this working on window and if yes then in which software we have to use it

**Comment by hellloxiaotian** [comment]
At 2020-10-03 02:55:49, "Waleed Ahmed" <notifications@github.com> wrote:

hi i am tring to run your code in pycharm but there is many error as you use ubuntu so kindly tell me is this working on window and if yes then in which software we have to use it

**Comment by Waleed-Ahmed-Khan** [comment]
please sir tell me the i have to do it actually I am new  int his field so
kindly help me tell me if I use visual studio 2019 then is it run on it and
is keras is avalbie in python because I download keras but it is c++ file

**Comment by hellloxiaotian** [comment]
Dear Mr or Miss,
       Visual studion with C++ cannot deal with deep learning task. 
       You may configure the platform with windows. However, it is more troublesome than ubuntu.
       Thus, I suggest you use ubuntu to configure the experimental enviroment.  
       My BRDNet is configured as follows. 
       Tensorflow 1.3.0
      Keras 2.0
     Numpy 
     Opencv 2 
     Python 2.7 
    Cuda 8.0
    Cudnn 7.5 
   Ubuntu 14.04


 Best wishes,
Chunwei 
















At 2020-10-03 20:19:13, "Waleed Ahmed" <notifications@github.com> wrote:

please sir tell me the i have to do it actually I am new int his field so
kindly help me tell me if I use visual studio 2019 then is it run on it and
is keras is avalbie in python because I download keras but it is c++ file

**Comment by Waleed-Ahmed-Khan** [comment]
thank you very much sir thank you soo much

**Comment by Waleed-Ahmed-Khan** [comment]
sir i didnot use ubuntu so is there any software who run the files and give
us table to result or there is any build in command promt system to run the
programme and het the result
